@startuml
start

skinparam backgroundColor #E6E6E6

skinparam activity {
  BackgroundColor #E6E6E6
  BorderColor #666666
}

skinparam defaultFontColor #333333
skinparam ArrowColor #555555
:Enable aspect mechanism in Spring app;
note right
Annotate configuration class
with @EnableAspectJAutoProxy
end note

:Create a new class and annotate with @Aspect;
note right
Use @Bean or stereotype annotations
to add a bean in the Spring context
end note

:Define a method with aspect logic;
note right
Tell Spring when and which methods
to intercept using advice annotation
end note

:Implement the aspect logic;

stop
@enduml
