@startuml

skinparam backgroundColor #E6E6E6

skinparam activity {
  BackgroundColor #E6E6E6
  BorderColor #666666
}

skinparam defaultFontColor #333333
skinparam ArrowColor #555555
actor Main
participant LoggingAspect
participant SecurityAspect
participant CommentService

Main -> LoggingAspect : main()
note right of LoggingAspect : 1. The LoggingAspect is the first to intercept the call.

LoggingAspect -> SecurityAspect : log()
note right of SecurityAspect : 2. The LoggingAspect delegates to SecurityAspect.

SecurityAspect -> CommentService : secure()
note right of CommentService : 3. The SecurityAspect executes and delegates to the intercepted method.

CommentService --> SecurityAspect : publishComment()
note left of SecurityAspect : 4. The intercepted method returns to the SecurityAspect.

SecurityAspect --> LoggingAspect
note left of LoggingAspect : 5. The SecurityAspect returns to LoggingAspect.

LoggingAspect --> Main
note left of Main : 6. The LoggingAspect returns to main().
@enduml
